apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.hookConfigs.kube }}
{{ (.Files.Glob "hooks/kube/*").AsConfig | indent 2 }}
{{- end }}
{{- if .Values.hookConfigs.aws-s3 }}
{{ (.Files.Glob "hooks/aws-s3/*").AsConfig | indent 2 }}
{{- end }}