{{- if eq .Values.serviceAccount "True" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "fullname" . }}-secret-updater
rules:
- apiGroups: [""]
  resources:
    - secrets
  resourceNames:
    - {{ .Values.certSecret }}
    - {{ .Values.tlsSecret }}
    - {{ .Values.acmeSecret }}
  verbs:
    - update
    - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname" . }}-secret-updater
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "fullname" . }}-secret-updater
  apiGroup: rbac.authorization.k8s.io
{{- end }}